#!/usr/bin/env python

"""

  File name: PlotResults.py
  Author: Alexis Leautier
  Python Version: 2.7
  Description: PlotResults.py uses the csv files generated by the cpp path planning scripts in
    order to plot a visualization of the results of the search. As this file is an executable,
    it can be launched directly from a command line without arguments from RRT-Path-Planning
    as "VisualizationTools/PlotResults.py". 

"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import itertools
import ast 


# Initialize figure 
fig, ax = plt.subplots()
ax.set_aspect('equal')

# Read data from Tree.csv into TreeXY
fieldnames = ['x', 'y']
TreePath = 'Results/Tree.csv'
TreeXY= {}

with open(TreePath, 'r+') as csvfile:
    for field in fieldnames:
        TreeXY[field] = []
        
    for row in itertools.islice(csvfile, 1, None):
            values = list(row.strip('\n').split(","))
            for i, value in enumerate(values):
                if (not value):
                    continue 
                if (value != value ):
                    value = '0'
                nValue = ast.literal_eval(value)
                TreeXY.get(fieldnames[i]).append(nValue)

# Plot Tree points
ax.plot(TreeXY['x'], TreeXY['y'], 'o', markeredgecolor="None", color='#43d5ef', ms = 2.7)

# Read data from Trajectory.csv into TrajXY
TrajPath = 'Results/Trajectory.csv'
TrajXY = {}

with open(TrajPath, 'r+') as csvfile:
    for field in fieldnames:
        TrajXY[field] = []
        
    for row in itertools.islice(csvfile, 1, None):
            values = list(row.strip('\n').split(","))
            for i, value in enumerate(values):
                if (not value):
                    continue 
                if (value != value):
                    value = '0'
                nValue = ast.literal_eval(value)
                TrajXY.get(fieldnames[i]).append(nValue)

# Plot Trajectory and mark starting point with a black X
ax.plot(TrajXY['x'], TrajXY['y'], color='#43ef5f', lw = 3) 
ax.plot(TrajXY['x'][-1], TrajXY['y'][-1], 'xk', ms = 5)
                
# Read data from Obstacles.csv into Obstacles
fieldnames = ['LBX', 'LBY', 'width', 'length']
ObsPath = 'Results/Obstacles.csv'
Obstacles = {}

with open(ObsPath, 'r+') as csvfile:
    for field in fieldnames:
        Obstacles[field] = []
        
    for row in itertools.islice(csvfile, 0, None):
            values = list(row.strip('\n').split(","))
            for i, value in enumerate(values):
                if (not value):
                    continue 
                if (value != value):
                    value = '0'
                nValue = ast.literal_eval(value)
                Obstacles.get(fieldnames[i]).append(nValue)
                

for i in range(len(Obstacles['LBX'])):
    ax.add_patch(patches.Rectangle((Obstacles['LBX'][i], Obstacles['LBY'][i]),
                               Obstacles['width'][i],Obstacles['length'][i],
                               facecolor = '#ff3700', edgecolor = "None"))

# Plot Obstacles
goal = plt.Circle((75,75), 1, color='#00ff90')
ax.add_artist(goal)

# Show plot
plt.show()
